//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NppPowerTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NppPowerTools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa
        ///aah
        ///aal
        ///aalii
        ///aardvark
        ///aardvarks
        ///aardwolf
        ///aardwolves
        ///aargh
        ///aarrghh
        ///aasvogel
        ///aasvogels
        ///ab
        ///aba
        ///abaca
        ///abacas
        ///abaci
        ///aback
        ///abacus
        ///abacuses
        ///abaft
        ///abalone
        ///abalones
        ///abampere
        ///abamperes
        ///abandon
        ///abandoned
        ///abandonee
        ///abandoning
        ///abandons
        ///abase
        ///abased
        ///abasement
        ///abases
        ///abash
        ///abashed
        ///abashes
        ///abashing
        ///abashment
        ///abashments
        ///abasing
        ///abatable
        ///abate
        ///abated
        ///abatement
        ///abatements
        ///abates
        ///abating
        ///abatis
        ///abator
        ///abators
        ///abattis
        ///abattises
        ///abattoir
        ///abattoirs
        ///abaxial
        ///abba
        ///abbacies [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à
        ///abandonner
        ///abattre
        ///abri
        ///absence
        ///absolu
        ///absolument
        ///accent
        ///accepter
        ///accompagner
        ///accomplir
        ///accord
        ///accorder
        ///accrocher
        ///accuser
        ///acheter
        ///achever
        ///acte
        ///action
        ///admettre
        ///adresser
        ///affaire
        ///affirmer
        ///afin
        ///de
        ///âge
        ///âgé
        ///agent
        ///agir
        ///agiter
        ///ah
        ///aide
        ///aider
        ///aile
        ///ailleurs
        ///aimer
        ///ainsi
        ///air
        ///ajouter
        ///aller
        ///allumer
        ///alors
        ///âme
        ///amener
        ///ami
        ///amour
        ///amuser
        ///an
        ///ancien
        ///anglais
        ///anglais
        ///angoisse
        ///animal
        ///animer
        ///année
        ///annoncer
        ///apercevoir
        ///apparaître
        ///apparence
        ///appartement
        ///appartenir
        ///appel
        ///appe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consetetur
        ///sadipscing
        ///elitr
        ///sed
        ///diam
        ///nonumy
        ///eirmod
        ///tempor
        ///invidunt
        ///ut
        ///labore
        ///et
        ///dolore
        ///magna
        ///aliquyam
        ///erat
        ///sed
        ///diam
        ///voluptua
        ///at
        ///vero
        ///eos
        ///et
        ///accusam
        ///et
        ///justo
        ///duo
        ///dolores
        ///et
        ///ea
        ///rebum
        ///stet
        ///clita
        ///kasd
        ///gubergren
        ///no
        ///sea
        ///takimata
        ///sanctus
        ///est
        ///lorem
        ///ipsum
        ///dolor
        ///sit
        ///amet
        ///lorem
        ///ipsum
        ///dolor
        ///sit
        ///amet
        ///consetetur
        ///sadipscing
        ///elitr
        ///sed
        ///diam
        ///nonumy
        ///eirmod
        ///tempor
        ///invidunt
        ///ut
        ///labore
        ///et
        ///dolore
        ///magna
        ///aliquyam
        ///erat
        ///sed
        ///diam
        ///voluptua
        ///at
        ///vero
        ///eos
        ///et
        ///accusam
        ///e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Latin {
            get {
                return ResourceManager.GetString("Latin", resourceCulture);
            }
        }
    }
}
