//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NppPowerTools {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NppPowerTools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à aa
        ///aah
        ///aal
        ///aalii
        ///aardvark
        ///aardvarks
        ///aardwolf
        ///aardwolves
        ///aargh
        ///aarrghh
        ///aasvogel
        ///aasvogels
        ///ab
        ///aba
        ///abaca
        ///abacas
        ///abaci
        ///aback
        ///abacus
        ///abacuses
        ///abaft
        ///abalone
        ///abalones
        ///abampere
        ///abamperes
        ///abandon
        ///abandoned
        ///abandonee
        ///abandoning
        ///abandons
        ///abase
        ///abased
        ///abasement
        ///abases
        ///abash
        ///abashed
        ///abashes
        ///abashing
        ///abashment
        ///abashments
        ///abasing
        ///abatable
        ///abate
        ///abated
        ///abatement
        ///abatements
        ///abates
        ///abating
        ///abatis
        ///abator
        ///abators
        ///abattis
        ///abattises
        ///abattoir
        ///abattoirs
        ///abaxial
        ///abba
        ///abbacies [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à à
        ///abandonner
        ///abattre
        ///abri
        ///absence
        ///absolu
        ///absolument
        ///accent
        ///accepter
        ///accompagner
        ///accomplir
        ///accord
        ///accorder
        ///accrocher
        ///accuser
        ///acheter
        ///achever
        ///acte
        ///action
        ///admettre
        ///adresser
        ///affaire
        ///affirmer
        ///afin
        ///de
        ///âge
        ///âgé
        ///agent
        ///agir
        ///agiter
        ///ah
        ///aide
        ///aider
        ///aile
        ///ailleurs
        ///aimer
        ///ainsi
        ///air
        ///ajouter
        ///aller
        ///allumer
        ///alors
        ///âme
        ///amener
        ///ami
        ///amour
        ///amuser
        ///an
        ///ancien
        ///anglais
        ///anglais
        ///angoisse
        ///animal
        ///animer
        ///année
        ///annoncer
        ///apercevoir
        ///apparaître
        ///apparence
        ///appartement
        ///appartenir
        ///appel
        ///appe [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à consetetur
        ///sadipscing
        ///elitr
        ///sed
        ///diam
        ///nonumy
        ///eirmod
        ///tempor
        ///invidunt
        ///ut
        ///labore
        ///et
        ///dolore
        ///magna
        ///aliquyam
        ///erat
        ///sed
        ///diam
        ///voluptua
        ///at
        ///vero
        ///eos
        ///et
        ///accusam
        ///et
        ///justo
        ///duo
        ///dolores
        ///et
        ///ea
        ///rebum
        ///stet
        ///clita
        ///kasd
        ///gubergren
        ///no
        ///sea
        ///takimata
        ///sanctus
        ///est
        ///lorem
        ///ipsum
        ///dolor
        ///sit
        ///amet
        ///lorem
        ///ipsum
        ///dolor
        ///sit
        ///amet
        ///consetetur
        ///sadipscing
        ///elitr
        ///sed
        ///diam
        ///nonumy
        ///eirmod
        ///tempor
        ///invidunt
        ///ut
        ///labore
        ///et
        ///dolore
        ///magna
        ///aliquyam
        ///erat
        ///sed
        ///diam
        ///voluptua
        ///at
        ///vero
        ///eos
        ///et
        ///accusam
        ///e [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Latin {
            get {
                return ResourceManager.GetString("Latin", resourceCulture);
            }
        }
    }
}
